[project]
name = "metrics"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "javalang>=0.13.0",
    "networkx>=3.4.2",
    "pandas>=2.2.3",
    "scipy>=1.15.2",
    "tqdm>=4.67.1",
]
